use Assistour;

SELECT DISTINCT HOTEL.IDHOT, HOTEL.NOM 
FROM HOTEL 
INNER JOIN HEBERGER 
ON HOTEL.IDHOT = HEBERGER.IDHOT 
INNER JOIN DOSSIERSINISTRE 
ON HEBERGER.IDDS = DOSSIERSINISTRE.IDDS 
WHERE DOSSIERSINISTRE.IDCON = 1;

SELECT SUM(NBNUITEE) 
FROM HEBERGER
INNER JOIN DOSSIERSINISTRE 
ON HEBERGER.IDDS = DOSSIERSINISTRE.IDDS 
WHERE DOSSIERSINISTRE.IDCON = 1;
